[External]
"SteamMatchMakingServers"=revSrvBrowser.dll
SteamMatchMakingServers=revSrvBrowser.dll
"SteamMatchMaking"=revSrvBrowser.dll

[Emulator]
CacheEnabled=False
Language=English
Logging=False
#SteamDll=Steam_orig.dll
SteamClient=True
SteamUser=CSREVO
ForceRevClient=False

[Log]
FileSystem=False
Account=False
UserID=False

[steamclient]
PlayerName=<CS Revo> Player
Logging=False
#ClientDLL=steamclient_orig.dll

[GameServer]
AllowOldRev=True
AllowUnknown=True
AllowCrackedSteam=True
AllowLegitSteam=True